title: LGs GitHub Blog
author: GitHub User
email: alliswell@endswell.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will take you to places you have never been!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
